StockSim/StockSim/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    url('', include('accounts.urls'), name='home'),
    url('portfolio/', include('portfolio.urls'), name='portfolio'),
    path('admin/', admin.site.urls),
    url('trader/', include('trader.urls'), name='trader'),
]

StockSim/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns=[
    path('login/', views.loginUser, name='loginUser'),
    path('register/', views.register, name='register'),
    path('logout/', views.logoutUser, name='logoutUser'),
    path('profile/', views.userProfile, name='userProfile'),
    path('', views.HomeView.as_view(), name='home'),
]

StockSim/portfolio/urls.py
from django.urls import path
from . import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.IndexView.as_view(), name='home'),
]

StockSim/trader/urls.py
from django.urls import path

from . import views

app_name = 'trader'
urlpatterns=[
    path('', views.MarketView.as_view(), name='lookup'),
    path('trade/', views.TradeView.as_view(), name='trade'),
]

StockSim/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django_cryptography.fields import encrypt

from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rhoodID = encrypt(models.CharField(max_length=50))
    rhoodPWD = encrypt(models.CharField(max_length=50))
    rhQ = encrypt(models.CharField(max_length=50))

def create_account(sender, **kwargs):
    userName = kwargs["instance"]
    if kwargs["created"]:
        account = Account(user=userName)
        account.save()

post_save.connect(create_account, sender=User)

StockSim/portfolio/models.py
from django.db import models
from django.conf import settings

class Portfolio(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    balance = models.FloatField(default=0.0)

class Position(models.Model):
    name = models.CharField(max_length=100)
    symbol = models.CharField(max_length=10)
    qantity = models.IntegerField(default=0)
    price = models.FloatField(default=0.0)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.PROTECT) #FK link

    def __str__(self):
        return self.symbol

class Transaction(models.Model):
    timestamp = models.DateTimeField(auto_now_add=True)
    actionType = models.CharField(max_length=4, choices=(('BUY','Buy'),('SELL','Sell'),)) # buy/sell
    quantity = models.IntegerField()
    symbol = models.CharField(max_length=10)
    actionPrice = models.FloatField(default=0.0)
    portfolio = models.ForeignKey(Portfolio, on_delete=models.PROTECT) #FK link to portfolio

StockSim/trader/models.py
from django.db import models

# Create your models here.

StockSim/accounts/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import Account

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1', 'password2']
        error_messages = {
            'email': {
                'unique': 'My Custom Error Message here !!!',
            },
        }

class SetupAccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ['rhoodID', 'rhoodPWD', 'rhQ']

StockSim/accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import Group
from django.views import generic

from django.shortcuts import render, redirect
from .decorators import unauthenticated_user, allowed_users
from .forms import CreateUserForm
from .models import Account
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import HttpResponse

import pyEX as p
import os

#@unauthenticated_user
def loginUser(request):
    #form = CreateUserForm()
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('accounts:home')
        else:
            messages.info(request, 'Incorrect Username/Password')
    context = {} 
    return render(request, 'accounts/login.html', context=context)

def register(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account successfully created for user: {}'.format(form.cleaned_data.get('username')))
            return redirect('accounts:loginUser')
    
    context = {'form':form} 
    return render(request, 'accounts/register.html', context=context)

def logoutUser(request):
    logout(request)
    return redirect('accounts:loginUser' )

@login_required(login_url='accounts:loginUser')
#@allowed_users(allowed_roles=[])
def userProfile(request):
    context = {}
    return render(request, 'accounts/profile.html', context)

@method_decorator(login_required, name='dispatch')
class HomeView(generic.ListView):
    template_name='accounts/index.html'

    def get(self, request):
        context={}
        accountDetails = Account.objects.get(user=request.user)
        if not accountDetails.rhoodID or not accountDetails.rhoodPWD or not accountDetails.rhQ:
            context['newUser'] = True
        #TODO: now that we know if its a new user, we must get the user to provide their RH credentials if they are new
        #This should be displayed as a modal
        
        
        
        token=os.environ['API_TOKEN']
        platform=os.environ['API_PLATFORM']
        c=p.Client(api_token=token, version=platform)
        dow=c.quote('DOW')
        sp500=c.quote('SPY')
        nasdaq=c.quote('IWM')
        context['current']={
            'dow':{'price':dow['latestPrice'], 'change':dow['changePercent']}, 
            'sp500':{'price':sp500['latestPrice'], 'change':sp500['changePercent']}, 
            'nasdaq':{'price':nasdaq['latestPrice'], 'change':nasdaq['changePercent']}
            }
        #return HttpResponse(context)
        return render(request, self.template_name, context)

StockSim/portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.views.generic import ListView

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accounts.decorators import allowed_users

@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name='portfolio/index.html'
    queryset = ''

    def get(self, request):
        return render(request, 'portfolio/index.html')

StockSim/trader/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.views.generic import ListView
import environ
#from Robinhood import Robinhood
from pyrh import Robinhood

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from accounts.decorators import allowed_users
from accounts.models import Account

@method_decorator(login_required, name='dispatch')
class MarketView(generic.ListView):
	template_name='trader/lookup.html'
	queryset = ''

	def get(self, request):
		#return HttpResponse(request.user.id)
		#env = environ.Env(DEBUG=(bool, False))
		# reading .env file
		#environ.Env.read_env()
		currentUser = Account.objects.get(user=request.user)
		my_trader = Robinhood()
		my_trader.login(username=currentUser.rhoodID, password=currentUser.rhoodPWD, qr_code=currentUser.rhQ)
		data=my_trader.portfolios()
		my_trader.logout()
		return HttpResponse(data)
		context={}
		return render(request, self.template_name, context)

@method_decorator(login_required, name='dispatch')
class TradeView(generic.ListView):
	template_name='trader/trade.html'
	queryset = ''

StockSim/accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} StockSim {% endblock title %}
{% block title2 %} StockSim {% endblock title2 %}
{% block title3 %} StockSim {% endblock title3 %}


{% block Page-View %} 


{% if newUser %}
<body onLoad="$('#my-modal').modal('show');">
  <div class="modal fade" id="my-modal">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Welcome to StockSim {{request.user}}!</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p> Since this is your first time lets setup your robinhood account&hellip;</p>
          <form action="" method="post">
            {% csrf_token %}
            
          </form>

        </div>
        <div class="modal-footer center">
          
          <button type="button" class="btn btn-primary">Save Account Info</button>
        </div>
      </div>
      <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
  </div>
  <!-- /.modal -->
</body>
{% else %}
  <div class="card-footer">
      <div class="row">
        <!-- /.col -->
        {% for x,v in current.items %}
          <div class="col-sm-3 col-6">
            <div class="description-block border-right">
                {% if v.change == 0 %}
                <span class="description-percentage text-warning">
                  <i class="fas fa-caret-left"></i>
                  {{v.change}}%
                </span>
                {% endif %}
                {% if v.change > 0 %}
                <span class="description-percentage text-success">
                  <i class="fas fa-caret-up"></i>
                  {{v.change}}%
                </span>
                {% endif %}
                {% if v.change < 0 %}
                <span class="description-percentage text-danger">
                  <i class="fas fa-caret-down"></i>
                  {{v.change}}%
                </span>
                {% endif %}
              <h5 class="description-header">${{v.price}}</h5>
              <span class="description-text">{{x}}</span>
            </div>
            <!-- /.description-block -->
          </div>
        {% endfor %}
      </div>
      <!-- /.row -->
    </div>
{% endif %}
{% endblock Page-View%}

StockSim/accounts/templates/accounts/register.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>StockSim | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition register-page">
<div class="register-box">
  <div class="register-logo">
    <a href=""><b>Stock</b>Sim</a>
  </div>

  <div class="card">
    <div class="card-body register-card-body">
      <p class="login-box-msg">Register a new membership</p>

      <form action="" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
            <div>
                {{form.username}}
            </div>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <div>
              {{form.first_name}}
          </div>
        <div class="input-group-append">
          <div class="input-group-text">
            <span class="fas fa-user"></span>
          </div>
        </div>
      </div>
      <div class="input-group mb-3">
        <div>
            {{form.last_name}}
        </div>
      <div class="input-group-append">
        <div class="input-group-text">
          <span class="fas fa-user"></span>
        </div>
      </div>
    </div>
        <div class="input-group mb-3">
            <div class="">
                {{form.email}}
            </div>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            <div class="">
                {{form.password1}}
            </div>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            <div class="">
                {{form.password2}}
            </div>
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        {{form.errors}}
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="agreeTerms" name="terms" value="agree">
              <label for="agreeTerms">
               I agree to the <a href="#">terms</a>
               <!-- Eventually link to terms in popup modal -->
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Register</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <a href="{% url 'accounts:loginUser' %}" class="text-center">I already have a membership</a>
    </div>
    <!-- /.form-box -->
  </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

<script>
    var form_fields = document.getElementsByTagName('input')
    form_fields[1].placeholder='Username';
    form_fields[2].placeholder='First Name';
    form_fields[3].placeholder='Last Name';
    form_fields[4].placeholder='Email';
    form_fields[5].placeholder='Enter password';
    form_fields[6].placeholder='Re-enter Password';


    for (var field in form_fields){	
    form_fields[field].className += ' form-control form-control-user'
    }
  </script>

</body>
</html>

StockSim/portfolio/templates/portfolio/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %} portfolio {% endblock title %}
{% block title2 %} portfolio {% endblock title2 %}
{% block title3 %} portfolio {% endblock title3 %}
{% block Page-View %} 

{% endblock Page-View%}

StockSim/templates/base.html
<!DOCTYPE html>
{% load static%}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>StockSim | {% block title %}Holder{% endblock title %}</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'accounts:home' %}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Messages Dropdown Menu -->
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
          <img src="{% static 'dist/img/defaultUser.png' %}" class="user-image img-circle elevation-2" alt="User Image">
          <span class="d-none d-md-inline">{{request.user}}</span>
        </a>
        <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <!-- User image -->
          <li class="user-header bg-primary">
            <img src="{% static 'dist/img/defaultUser.png' %}" class="img-circle elevation-2" alt="User Image">

            <p>
                {{request.user.first_name}} {{request.user.last_name|make_list|first}} - Web Developer
              <small>Member since {{request.user.date_joined.date}}</small>
            </p>
          </li>
          <!-- Menu Body -->
          <li class="user-body">
            <div class="row">
              <div class="col-4 text-center">
                <a href="#">$---</a>
              </div>
              <div class="col-4 text-center">
                <a href="{%url 'portfolio:home' %}">Portfolio</a>
              </div>
            </div>
            <!-- /.row -->
          </li>
          <!-- Menu Footer-->
          <li class="user-footer">
            <a href="#" class="btn btn-default btn-flat">Profile</a>
            <a href="{% url 'accounts:logoutUser' %}" class="btn btn-default btn-flat float-right">Sign out</a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{% url 'accounts:home' %}" class="brand-link">
      <img src="{% static 'dist/img/AdminLTELogo.png' %}"
           alt="AdminLTE Logo"
           class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">StockSim</span>
    </a>


    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview">
            <a href="{%url 'portfolio:home' %}" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Portfolio
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%url 'portfolio:home' %}" class="nav-link active">
                  <i class="far fa-circle nav-icon"></i>
                  <p>My Portfolio</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="#" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Open Trades</p>
                </a>
              </li>
            </ul>
          </li>
          
          <li class="nav-header">Stock Trading</li>
          <li class="nav-item">
            <a href="{%url 'trader:lookup' %}" class="nav-link">
              <i class="nav-icon fa fa-line-chart"></i>
              <p>
                View Market
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon far fa-image"></i>
              <p>
                Link 2
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>{% block title2 %}{% endblock title2 %}</h1>
          </div>
          {% comment %}
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">{% block title3 %}{% endblock title3 %}</li>
            </ol>
          </div>
          {% endcomment %}
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
	
	{% block Page-View %}
      
  {% endblock Page-View %}
	  
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 0.0.1
    </div>
    <strong>Copyright &copy; 2014-2019 StockSim.</strong> All rights
    reserved.
    <a href="https://iexcloud.io">Data provided by IEX Cloud</a>
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
</body>
</html>

StockSim/templates/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>StockSim | Log in</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
  <!-- Google Font: Source Sans Pro -->
  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href=""><b>Stock</b>Sim</a>
  </div>
  <!-- /.login-logo -->
  <div class="card">
    <div class="card-body login-card-body">
      <div class="text-center">
        <p class="login-box-msg">Sign in to start your session</p>
        {% for message in messages %}
          <p id="messages">{{message}}</p>
        {% endfor %}
      </div>
      <form class="user" method="post">
        {% csrf_token %}
        <div class="input-group mb-3">
          <input type="text" class="form-control" name="username" placeholder="Username">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-user"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
          <input type="password" name="password" class="form-control" placeholder="Password">
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-8">
            <div class="icheck-primary">
              <input type="checkbox" id="remember">
              <label for="remember">
                Remember Me
              </label>
            </div>
          </div>
          <!-- /.col -->
          <div class="col-4">
            <button type="submit" class="btn btn-primary btn-block">Sign In</button>
          </div>
          <!-- /.col -->
        </div>
      </form>

      <p class="mb-0">
        <a href="{% url 'accounts:register' %}" class="text-center">Register a new membership</a>
      </p>
    </div>
    <!-- /.login-card-body -->
  </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>
</html>

StockSim/trader/templates/trader/lookup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Market Search {% endblock title %}
{% block title2 %} Market Search {% endblock title2 %}
{% block title3 %} Market Search {% endblock title3 %}
{% block Page-View %} 

{% endblock Page-View%}

StockSim/trader/templates/trader/trade.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Trade {% endblock title %}
{% block title2 %} Trade {% endblock title2 %}
{% block title3 %} Trade {% endblock title3 %}
{% block Page-View %} 

{% endblock Page-View%}